name: Periodic health check

on:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  periodic_healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL health
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://fsopokedex-vol.onrender.com/health
          max-attempts: 3
          retry-delay: 7s